version: '3.8'
services:
  djangopg_db:
    build:
      dockerfile: psql-Dockerfile
      context: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dbpass
    container_name: pg-ext-db
  tox:
    build:
      dockerfile: tox-Dockerfile
      context: .
    environment:
      POSTGRES_URL: postgresql://dbuser:dbpass@djangopg_db:5432/test_db
    command: bash -c "while ! nc -w 1 -z djangopg_db 5432; do sleep 0.1; done; cd /home/root/; python manage.py migrate && tox -q -e py27"
    container_name: tox-pg-ext
    volumes:
      - .:/home/root/
    depends_on:
      - djangopg_db
